name: "[security] | Snyk Security Check"

on:
  push:
    branches:
      - main
      # - dev
      # Add more branch names if needed

jobs:
  snyk-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Snyk CLI to check for security issues
      uses: snyk/actions/setup@a1346e4eaf761d462da22c34c681dc06849b6851

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Change this to your version

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # If Snyk CLI is not installed on the runner, you can install it as follows:
    - name: Install Snyk CLI
      run: npm install -g snyk@latest

    - name: Snyk Auth using API
      run: snyk auth ${{ secrets.SNYK_TOKEN }} -d

    # - name: file-converter | pip install
    #   run: python3 -m pip install -r services/file-converter/requirements.txt

    # - name: streamlit-dashboard | pip install 
    #   run: python3 -m pip install -r services/streamlit-dashboard/streamlit/requirements.txt

    # - name: file-converter |  Snyk Test 
    #   run: snyk test services/file-converter --severity-threshold=high

    # - name: streamlit-dashboard |  Snyk Test 
    #   run: snyk test services/streamlit-dashboard/streamlit --severity-threshold=high
